version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    network_mode: zabbix-net        
    environment:
      MYSQL_DATABASE: 'zabbix'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: "Asia/Tehran"
    ports:
      - 3306:3306
    volumes:
      - /root/docker/zabbix/mysql-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin', '--default-authentication-plugin=mysql_native_password']

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    restart: unless-stopped
    network_mode: zabbix-net
    environment:
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: "zabbix" 
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tehran"
    ports:
      - '10051:10051'
    volumes:
      - /root/docker/zabbix/zabbix-data:/etc/zabbix

  nginx:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: nginx
    restart: unless-stopped
    network_mode: zabbix-net
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix" 
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tehran"
      PHP_TZ: "Asia/Tehran"
    ports:
      - '80:8080'
   
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    restart: unless-stopped
    network_mode: zabbix-net
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_HOSTNAME: "Zabbix server - with docker"
      TZ: "Asia/Tehran"
   

volumes: 
  my-db:
  zabbix-data:
